apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-inventory-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: car-inventory-service
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: car-inventory-service
    spec:
      containers:
        - image: car-inventory-service-image:v1
          imagePullPolicy: IfNotPresent # looks for image locally, then at configured public registries
          name: car-inventory-service-container
          ports:
            - containerPort: 8080
